import math

# Internal render resolution (fixed)
RENDER_WIDTH, RENDER_HEIGHT = 800, 600
RENDER_RES = (RENDER_WIDTH, RENDER_HEIGHT)

# Window size (initial, can be resized)
WIDTH, HEIGHT = 1280, 720
RES = (WIDTH, HEIGHT)

HALF_WIDTH = RENDER_WIDTH // 2
HALF_HEIGHT = RENDER_HEIGHT // 2

FPS = 0

PLAYER_POS = 1.5, 5
PLAYER_ANGLE = 0
PLAYER_SPEED = 0.004
PLAYER_ROT_SPEED = 0.002
PLAYER_SIZE_SCALE = 60
PLAYER_MAX_HEALTH = 100
PLAYER_START_LIVES = 5

MOUSE_SENSITIVITY = 0.0003
MOUSE_MAX_REL = 40
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WIDTH - MOUSE_BORDER_LEFT

FLOOR_COLOR = (30, 30, 30)
CEILING_COLOR = (128, 128, 128)

FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = RENDER_WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FOV / NUM_RAYS
MAX_DEPTH = 20

SCREEN_DIST = HALF_WIDTH / math.tan(HALF_FOV)
SCALE = RENDER_WIDTH // NUM_RAYS

TEXTURE_SIZE = 256
HALF_TEXTURE_SIZE = TEXTURE_SIZE // 2

# Level progression
BASE_ENEMIES = 10         # enemies on level 1
ENEMIES_PER_LEVEL = 2     # additional enemies per level
MAX_LEVEL = 15